name: Deploy my Lamba Function

on:
  push:
     branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
           python-version: 3.8
      - name: Install Libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ] ; then pip install -r requirements.txt -t .; fi
      - name: Create Zip Bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: zipped-bundle
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://mys3bucketsgdasjhgdjhasgdhjgasjgj/${{ github.sha }}.zip
          
      
    

      
